install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('leaflet')
install.packages("corrplot")
install.packages("leaps" )
install.packages("dummies")
install.packages("leaps")
install.packages("forecast")
install.packages("gains")
install.packages("reshape")